apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: basic-node-js
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: basic-node-js
    app.kubernetes.io/part-of: test-app
  name: basic-node-js
  namespace: dsantra12
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: basic-node-js
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: basic-node-js
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:dsantra12-basic-node-js
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
